language: ruby
rvm:
- 2.2.2

install: gem install jekyll htmlproofer

before_script:
    - chmod +x ./script/cibuild

script: ./script/cibuild

env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
