# Site settings
title: Konstantin's Box
email: konstantinfarrell@gmail.com
description: >
    Hi I'm Konstantin. Welcome to my site.
baseurl: ""
url: "http://konstantinfarrell.github.io"
twitter_username: that_konstantin
github_username:  konstantinfarrell
permalink: /:year/:month/:title

# Build settings
markdown: kramdown
gems:
    - jekyll-feed
    - html-proofer

exclude: [vendor]
