# Site settings
title: Konstantin's Box
email: konstantinfarrell@gmail.com
description: >
    Konstantin is a full-stack web developer from Portland, Oregon.
    In his spare time he can be found tinkering away at some code or
    circuits, making music on whatever instrument he can find, or
    hacking away at about 4 projects at once.
    He also occasionally has a decent game of DotA.
baseurl: ""
url: "http://konstantinfarrell.github.io"
twitter_username: that_konstantin
github_username:  konstantinfarrell
permalink: /:year/:month/:title

# Build settings
markdown: kramdown
gems:
    - jekyll-feed
    - html-proofer

exclude: [vendor]
